name = "web-frontend"
primary_group = "tienda"
secondary_group = "frontend"
commands.start.run = "node server.js"
port = 5173
process_pattern = ""
commands.install.run = "echo installing web-frontend"
commands.build.run = "mise run build"
