name = "web-frontend"
primary_group = "tienda"
secondary_group = "frontend"
command_start = "node server.js"
port = 5173
process_pattern = ""
command_install = "echo installing web-frontend"
command_build = "mise run build"
